
import "@/styles/globals.css";
import Nav from '@/components/Nav';

export const metadata = {
  title: "Empresas X",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className='header'>
            <div className='logo'>
              <h1>Empresas X</h1>
            </div>
          </div>
        </header>

        <Nav />

        {children}
        <footer>
          <p>© 2025 Empresas X. Todos los derechos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
